
services:
  ping-setter:
    build: .
    container_name: ping-setter-bot
    env_file: .env
    volumes:
      - ./logs:/opt/ping_setter_hll/logs
    command: python manage.py send_ping
    restart: unless-stopped

